### PR TITLE
Update sample Xcode projects to build on glNext/master

### PR DESCRIPTION
**Pull request by ghost**
A couple of changes were made to make each of the samples building:
- `CinderAsio.h` needs to be included before anything else in the precompiled headers
- The precompiled headers need to grab `App.h` instead of `AppBasic.h`
- Update the Xcode project settings
- Add `CinderAsio.h` to the projects
- Link to both the CoreMedia and AV Foundation frameworks

### CODE REVIEW

**Comment by pizthewiz** [comment]
This needs the IOKit framework too, though I think the block might need some updates for the boost move.

**Comment by pizthewiz** [comment]
Yep, IOKit and the header path need tweaked but first changes to support the updates to `Buffer` need to be done.

**Comment by pizthewiz** [comment]
The `Buffer` change is tracked in #16

**Comment by pizthewiz** [comment]
Buffer bits sorted in ec8ce36, I'll make the Xcode project updates tonight for the new frameworks and what not.

**Comment by pizthewiz** [comment]
All the samples are now building for me with Cinder master.

**Comment by lucasvickers** [comment]
Is this ready for merge?  It's a shame the master branch won't build on current cinder.

**Comment by pizthewiz** [comment]
Good question, it was at the time but both Cinder and Cinder-ASIO seem to have a few commits since then.

**Comment by pizthewiz** [comment]
Seems to build and run just fine against the master branch of Cinder.

**Comment by lucasvickers** [comment]
Sorry! I Meant master branch @bantherewind's repo. I'd love to see the PR completed.

**Pull request closed without merging**
